name: simple-openvpn-client # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '0.3' # just for humans, typically '1.2+git' or '1.3.2'
summary: Just a simple OPENVPN client # 79 char long summary
description: |
  Place your OVPN certificate in the "/var/snap/openvpn-client-fast/common/" folder
  named "client.ovpn" then restart the app. 
  
confinement: strict # use 'strict' once you have the right plugs and slots
apps:
  vpn:  
        command: usr/sbin/openvpn
        plugs:
            - network
            - network-bind
            - network-control
            - firewall-control
  vpn-daemon:
        command: usr/sbin/openvpn  --config $SNAP_COMMON/client.ovpn 
        daemon: simple
        restart-condition: always
        restart-delay: 5s
        plugs:
            - network
            - network-bind
            - network-control
            - firewall-control


parts:
  my-part:
    # See 'snapcraft plugins'
    plugin: nil
    stage-packages:
       - openvpn
       - libatm-dev
